#!/usr/bin/env bash
#
# Generate a release signing key for the Android app.
#
#   ./scripts/make-keystore.sh
#   export OPENCODE_STORE_PASSWORD=... OPENCODE_KEY_PASSWORD=...
#   ./gradlew assembleRelease
#
# The keystore and keystore.properties are gitignored. The passwords are read
# from the environment at build time, so the secret never has to be written
# down anywhere this repo can see.
set -euo pipefail

KEYSTORE="${1:-opencode-release.jks}"
ALIAS="${2:-opencode}"
VALIDITY="${3:-10000}"   # ~27 years; Play requires validity past 2033

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }

command -v keytool >/dev/null || { echo "keytool not found (needs a JDK)" >&2; exit 1; }

read -rsp "Store password: " STORE_PW; echo
read -rsp "Key password:   " KEY_PW; echo

say "creating $KEYSTORE (validity $VALIDITY days)"
keytool -genkeypair -v \
    -keystore "$KEYSTORE" \
    -storetype JKS \
    -alias "$ALIAS" \
    -keyalg RSA -keysize 4096 \
    -validity "$VALIDITY" \
    -storepass "$STORE_PW" \
    -keypass "$KEY_PW" \
    -dname "CN=opencode android client, O=opencode, C=US"

cat > keystore.properties <<PROPS
# Gitignored. Generated by scripts/make-keystore.sh.
# The build prefers the OPENCODE_* environment variables over these values.
storeFile=$KEYSTORE
keyAlias=$ALIAS
PROPS

say "wrote keystore.properties (passwords deliberately omitted)"
say "now build with:"
printf '\n    export OPENCODE_STORE_PASSWORD=%q\n    export OPENCODE_KEY_PASSWORD=%q\n    ./gradlew assembleRelease\n\n' "$STORE_PW" "$KEY_PW"
printf '  Back up %s somewhere safe. Losing it means you can never update the\n' "$KEYSTORE"
printf '  app on a store or a release URL.\n'
